package com.be.electronic_store.constant;

public enum ExceptionEnum {

    OBJECT_NOT_FOUND_EXCEPTION,
    VALIDATION_EXCEPTION,
    CONFLICT_EXCEPTION,
    INTERNAL_SERVER_ERROR_EXCEPTION,
    BAD_REQUEST_EXCEPTION,
    PERMISSION_DENIED_EXCEPTION
}
